all:
	make -C multi_client
	make -C multi_server
install:
	make -C multi_client install
	make -C multi_server install
clean:
	make -C multi_client clean
	make -C multi_server clean
	rm -fr .tmp_versions
