
all:
	make -C client_proxy
	make -C client_tools
	make -C server_proxy
	make -C server_tools
clean:
	make -C client_proxy clean
	make -C client_tools clean
	make -C server_proxy clean
	make -C server_tools clean
