all:
	make -C multi_server_control
	make -C multi_config_control
install:
	make -C multi_server_control install
	make -C multi_config_control install
clean:
	make -C multi_server_control clean
	make -C multi_config_control clean
	rm -fr .tmp_versions
